---
- name: Install CycleCloud repo (Ubuntu)
  block:
    - name: Install prerequisites
      apt:
        name:
          - wget
          - gnupg2
        state: present

    - name: Add Microsoft GPG key
      shell: |
        wget -qO /usr/share/keyrings/microsoft.gpg https://packages.microsoft.com/keys/microsoft.asc
      args:
        creates: /usr/share/keyrings/microsoft.gpg

    - name: Add CycleCloud repository (bionic, since jammy is missing)
      copy:
        dest: /etc/apt/sources.list.d/cyclecloud.list
        content: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/cyclecloud bionic main"

    - name: Update APT cache
      apt:
        update_cache: yes

- name: Install Jetpack (Ubuntu)
  apt:
    name: "jetpack8={{ cc_version | default('latest') }}"
    state: present
    lock_timeout: 180

- name: Install dependencies
  apt:
    name:
      - jq
      - python3.10
      - python3.10-venv
    state: present
  become: yes
