project_name: d-apqx-hpc
location: eastus
resource_group: d-apqx-azhop-rg
anf:
  create: true
  homefs_size_tb: 4
  homefs_service_level: Standard
  dual_protocol: false
  alert_threshold: 80
mounts:
  home:
    type: anf
    mountpoint: /anfhome
    server: '{{anf_home_ip}}'
    export: '{{anf_home_path}}'
    options: '{{anf_home_opts}}'
admin_user: hpcadmin
azure_key_vault:
  name: apsdazhopkv
azure_storage_account:
  name: devapsazhopsstg
network:
  create_nsg: true
  vnet:
    name: hpcvnet
    address_space: 10.128.0.0/20
    subnets:
      frontend:
        name: frontend
        address_prefixes: 10.128.0.0/29
        create: true
      admin:
        name: admin
        address_prefixes: 10.128.0.16/28
        create: true
      netapp:
        name: netapp
        address_prefixes: 10.128.0.32/28
        create: true
      ad:
        name: ad
        address_prefixes: 10.128.0.8/29
        create: true
      bastion:
        address_prefixes: 10.128.3.0/26
        create: false
      compute:
        name: compute
        address_prefixes: 10.128.1.0/24
        create: true
      database:
        name: database
        address_prefixes: 10.128.2.0/26
private_dns:
  create: true
  name: hpc.azure
  registration_enabled: true
locked_down_network:
  public_ip: true
linux_base_image: canonical:0001-com-ubuntu-pro-focal:pro-20_04-lts-gen2:20.04.202502181 #canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:22.04.202502280
#linux image plan if required, format is publisher:product:name
linux_base_plan: canonical:0001-com-ubuntu-pro-focal:pro-20_04-lts-gen2
windows_base_image: MicrosoftWindowsServer:WindowsServer:2019-Datacenter-smalldisk:latest
jumpbox:
  vm_size: Standard_D2as_v4
ad:
  vm_size: Standard_D4as_v4
ondemand:
  vm_size: Standard_D8as_v4
  generate_certificate: true
grafana:
  vm_size: Standard_D2as_v4
scheduler:
  vm_size: Standard_D8as_v4
cyclecloud:
  vm_size: Standard_D4as_v4
  image: canonical:0001-com-ubuntu-pro-focal:pro-20_04-lts-gen2:20.04.202502181 #canonical:0001-com-ubuntu-minimal-focal-daily:minimal-20_04-daily-lts-gen2:20.04.202502040
  plan: canonical:0001-com-ubuntu-pro-focal:pro-20_04-lts-gen2
users:
  - { name: clusteradmin, uid: 10001, groups: [5001, 5002] }
  - { name: hpcuser, uid: 10002 }
  - { name: jared.brathwaite, uid: 10003, groups: [5001, 5002] }
  - { name: shreyas.ananthan, uid: 10005, groups: [5001, 5002] }
  - { name: sagar, uid: 10004, groups: [5001, 5002] }
usergroups:
  - name: Domain Users
    gid: 5000
  - name: az-hop-admins
    gid: 5001
    description: For users with azhop admin privileges
  - name: az-hop-localadmins
    gid: 5002
    description: For users with sudo right or local admin right on nodes
queue_manager: slurm
slurm:
  cyclecloud_slurm_version: 3.0.4
  accounting_enabled: false
  slurm_version: 23.02.5
  cluster_name: slurm_azhop
enroot:
  enroot_version: 3.4.1
authentication:
  user_auth: ad
  httpd_auth: basic
  # User mapping https://osc.github.io/ood-documentation/latest/reference/files/ood-portal-yml.html#ood-portal-generator-user-map-match
  # You can specify either a map_match or a user_map_cmd
  # Domain users are mapped to az-hop users with the same name and without the domain name
  # user_map_match: '^([^@]+)@mydomain.foo$'
  # If using a custom mapping script, update it from the ./playbooks/files directory before running the playbook
  # user_map_cmd: /opt/ood/ood_auth_map/bin/custom_mapping.sh
  # ood_auth_openidc:
  # OIDCProviderMetadataURL: https://sts.windows.net/{{tenant_id}}/.well-known/openid-configuration # for AAD use 'https://sts.windows.net/{{tenant_id}}/.well-known/openid-configuration'
  # OIDCClientID: b22391ca-be0d-4ded-bd82-363f6e9f3e97
  # OIDCRemoteUserClaim: unique_name # for AAD use 'unique_name'
  # OIDCScope: openid profile emaiil groups # for AAD use 'openid profile email groups'
  # OIDCPassIDTokenAs: serialized # for AAD use 'serialized'
  # OIDCPassRefreshToken: On # for AAD use 'On'
  # OIDCPassClaimsAs: environment # for AAD use 'environment'
  # OIDCStateMaxNumberOfCookies: [10, true] # in case of too many connections error for the same user set this to [10, true]
autoscale:
  idle_timeout: 1800
queues:
  - name: htc
    vm_size: Standard_F2s_v2
    max_core_count: 1024
    image: microsoft-dsvm:ubuntu-hpc:2204:latest
    EnableAcceleratedNetworking: false
    spot: false
    ColocateNodes: false
    idle_timeout: 300
    MaxScaleSetSize: 100

  - name: hpc
    vm_size: Standard_HB120-64rs_v3 #Standard_HB176-48rs_v4
    #max_core_count: 1000
    max_count: 16
    image: azhpc:azhop-desktop:ubuntu-20_04:2024.0305.1339
    EnableAcceleratedNetworking: true
    ColocateNodes: true
    idle_timeout: 300
    
  - name: cfd
    vm_size: Standard_HB176-96rs_v4
    #max_core_count: 1000
    max_count: 16
    image: azhpc:azhop-desktop:ubuntu-20_04:2024.0305.1339
    EnableAcceleratedNetworking: true
    ColocateNodes: true
    idle_timeout: 300

 # - name: h100
 #   vm_size: Standard_NC40ads_H100_v5
 #   max_core_count: 196
 #   image: azhpc:azhop-desktop:ubuntu-20_04:2024.0305.1339
 #   EnableAcceleratedNetworking: true
 #   ColocateNodes: true
 #   idle_timeout: 300
  

  - name: viz3d
    type: remoteviz
    vm_size: Standard_NV36ads_A10_v5
    max_count: 10
    max_core_count: 192
    image: microsoft-dsvm:ubuntu-2004:2004-gen2:25.02.13 #azhpc:azhop-desktop:ubuntu-20_04:2024.0305.1339
    ColocateNodes: false
    EnableAcceleratedNetworking: true
    max_hours: 12
    min_hours: 1
    idle_timeout: 300

  #- name: largeviz3d
  #  type: remoteviz
  #  description: "Large With GPU - Intended for shared sessions"
  #  shareable: true
  #  vm_size: Standard_NV72ads_A10_v5
  #  max_core_count: 192
  #  image: azhpc:azhop-desktop:ubuntu-20_04:2024.0305.1339
  #  ColocateNodes: false
  #  EnableAcceleratedNetworking: true
  #  max_hours: 12
  #  min_hours: 1

  - name: viz
    type: remoteviz
    vm_size: Standard_F4s_v2
    max_core_count: 1000
    image: azhpc:azhop-desktop:ubuntu-20_04:2024.0305.1339
    ColocateNodes: false
    EnableAcceleratedNetworking: true
    max_hours: 12
    min_hours: 1
    idle_timeout: 300
    
  - name: login
    type: login
    vm_size: Standard_F4s_v2
    initial_count: 1
    max_count: 1
    image: azhpc:azhop-desktop:ubuntu-20_04:2024.0305.1339
    ColocateNodes: false
    EnableAcceleratedNetworking: true
    idle_timeout: 300
    
image_gallery:
  create: false


applications:
  bc_codeserver:
    enabled: false
  bc_jupyter:
    enabled: false
  bc_amlsdk:
    enabled: false
  bc_rstudio:
    enabled: false
  bc_ansys_workbench:
    enabled: false
  bc_vmd:
    enabled: false
  bc_paraview:
    enabled: false
  bc_vizer:
    enabled: false
